[tasks.build]
install_crate = "mdbook"
command = "mdbook"
args = ["build"]

[tasks.serve]
install_crate = "mdbook"
command = "mdbook"
args = ["serve", "--open"]

[tasks.lint]
command = "pnpm"
args = ["textlint", "README.md", "src/"]
